name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up SDL3
        uses: libsdl-org/setup-sdl@main
        with:
          install-linux-dependencies: true
          version: 3-latest

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build
